version: "3"

volumes:
  pg_data:

services:
  datapusher:
    container_name: datapusher-plus
    build:
      context: ./datapusher-plus/0.13.2/
      dockerfile: Dockerfile

    ports:
      - "8800:8800"
    network_mode: "host"
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://datapusher_jobs:<YOUR_PASSWORD>@localhost/datapusher_jobs
      - WRITE_ENGINE_URL=postgresql://datapusher:<YOUR_PASSWORD>@localhost/datastore_default
