version: "3"

volumes:
  pg_data:

services:
  datapusher:
    container_name: datapusher-plus
    build:
      context: ./datapusher-plus/0.15.0/
      dockerfile: Dockerfile
    networks:
      - ckan-docker_default
    ports:
      - "8800:8800"
    network_mode: "host"
    restart: unless-stopped

networks:
  ckan-docker_default:
    external: true

